import type { ProvenanceReport } from '@shared/ipc/contract'

/**
 * The disclosure report (F-14.6) as Markdown: what an author hands to an editor or a
 * publisher who asks how much of the manuscript came from the AI. Pure over the report; the
 * handler picks the path and writes the file.
 */
export function renderDisclosure(
  report: ProvenanceReport,
  opts: { projectName: string; date: Date }
): string {
  const lines = [
    `# AI disclosure: ${opts.projectName}`,
    '',
    `Generated by MythScribe on ${isoDate(opts.date)}.`,
    '',
    `**AI-origin text:** ${report.projectPercent}% of the manuscript ` +
      `(${count(report.aiChars)} of ${count(report.totalChars)} characters).`,
    '',
    '| Scene | AI characters | Total characters | AI share |',
    '| --- | ---: | ---: | ---: |',
    ...report.documents.map(
      (doc) =>
        `| ${cell(doc.title)} | ${count(doc.aiChars)} | ${count(doc.totalChars)} | ${doc.percent}% |`
    ),
    '',
    '"AI-origin" means text the author accepted from an AI proposal through MythScribe\'s ' +
      'proposal review; nothing enters the manuscript without that acceptance. Once the author ' +
      'has edited a passage past half of the text they accepted, it is no longer counted as ' +
      'AI-origin: what remains is their rewrite.',
    ''
  ]
  return lines.join('\n')
}

/** The local calendar day as `YYYY-MM-DD`. */
function isoDate(date: Date): string {
  const pad = (n: number): string => String(n).padStart(2, '0')
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`
}

const count = (n: number): string => n.toLocaleString('en-US')

/** A title inside a Markdown table cell: pipes escaped, line breaks flattened. */
const cell = (title: string): string => title.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim()
