import { describe, expect, it } from 'vitest'
import type { ProvenanceReport } from '@shared/ipc/contract'
import { renderDisclosure } from './disclosure'

const REPORT: ProvenanceReport = {
  projectPercent: 12,
  aiChars: 1_234,
  totalChars: 10_000,
  documents: [
    { id: 's1', title: 'Scene 1', aiChars: 1_234, totalChars: 5_000, percent: 25, proposals: 2 },
    {
      id: 's2',
      title: 'Scene | two\nlines',
      aiChars: 0,
      totalChars: 5_000,
      percent: 0,
      proposals: 0
    }
  ]
}

describe('renderDisclosure (F-14.6)', () => {
  it('renders the title, date, totals, one table row per document, and the meaning of AI-origin', () => {
    const md = renderDisclosure(REPORT, {
      projectName: 'The Ridge',
      date: new Date(2026, 8, 15, 9, 30)
    })
    expect(md).toMatchInlineSnapshot(`
      "# AI disclosure: The Ridge

      Generated by MythScribe on 2026-09-15.

      **AI-origin text:** 12% of the manuscript (1,234 of 10,000 characters).

      | Scene | AI characters | Total characters | AI share |
      | --- | ---: | ---: | ---: |
      | Scene 1 | 1,234 | 5,000 | 25% |
      | Scene \\| two lines | 0 | 5,000 | 0% |

      "AI-origin" means text the author accepted from an AI proposal through MythScribe's proposal review; nothing enters the manuscript without that acceptance. Once the author has edited a passage past half of the text they accepted, it is no longer counted as AI-origin: what remains is their rewrite.
      "
    `)
  })

  it('renders an empty manuscript as 0% with only the table header', () => {
    const md = renderDisclosure(
      { projectPercent: 0, aiChars: 0, totalChars: 0, documents: [] },
      { projectName: 'Blank', date: new Date(2026, 0, 2) }
    )
    expect(md).toContain('**AI-origin text:** 0% of the manuscript (0 of 0 characters).')
    expect(md).toContain('2026-01-02')
    expect(md.split('\n').filter((line) => line.startsWith('|'))).toHaveLength(2)
  })
})
