import {
  BookMarked,
  Castle,
  Church,
  Cog,
  Crown,
  Feather,
  Flag,
  Flame,
  Folder,
  Gem,
  Globe,
  Landmark,
  Languages,
  Leaf,
  MapPin,
  PawPrint,
  Scroll,
  Shield,
  Ship,
  Skull,
  Sparkles,
  Star,
  Swords,
  Users,
  type LucideIcon
} from 'lucide-react'
import type { CategoryIcon } from '@shared/categories'

/** The lucide icon of each category icon (F-9.11): the section picker, the tab header, the dialogs. */
export const CATEGORY_ICON: Record<CategoryIcon, LucideIcon> = {
  users: Users,
  'map-pin': MapPin,
  globe: Globe,
  sparkles: Sparkles,
  shield: Shield,
  church: Church,
  'paw-print': PawPrint,
  gem: Gem,
  landmark: Landmark,
  scroll: Scroll,
  languages: Languages,
  cog: Cog,
  'book-marked': BookMarked,
  flag: Flag,
  crown: Crown,
  leaf: Leaf,
  swords: Swords,
  star: Star,
  ship: Ship,
  castle: Castle,
  feather: Feather,
  flame: Flame,
  skull: Skull,
  folder: Folder
}
