import type { Entity } from '@shared/ipc/contract'
import { NO_SHEET_SYNC } from '@shared/sheetSync'

/** Five entities across the three kinds, in `entity:list` order, for the entity tests (F-9.2). */
export const entityFixture: Entity[] = [
  {
    id: 'e-aldous',
    kind: 'character',
    name: 'Aldous',
    template: 'blank',
    fields: {},
    body: 'The old cartographer who taught Mara to read the stars.',
    image: null,
    tagId: null,
    aliases: [],
    origin: 'author',
    status: 'canon',
    extraFields: [],
    sync: NO_SHEET_SYNC,
    created: '2026-09-01T10:00:00.000Z',
    modified: '2026-09-01T10:00:00.000Z'
  },
  {
    id: 'e-mara',
    kind: 'character',
    name: 'Mara',
    template: 'structured',
    fields: { age: '27', appearance: 'Tall, with a scar across her left palm.' },
    body: null,
    image: null,
    tagId: null,
    aliases: [],
    origin: 'author',
    status: 'canon',
    extraFields: [],
    sync: NO_SHEET_SYNC,
    created: '2026-09-02T10:00:00.000Z',
    modified: '2026-09-03T11:30:00.000Z'
  },
  {
    id: 'e-forest',
    kind: 'setting',
    name: 'Dark Forest',
    template: 'structured',
    fields: { type: 'Wilderness', atmosphere: 'Silent and watchful.' },
    body: null,
    image: null,
    tagId: null,
    aliases: [],
    origin: 'author',
    status: 'canon',
    extraFields: [],
    sync: NO_SHEET_SYNC,
    created: '2026-09-02T10:00:00.000Z',
    modified: '2026-09-02T10:00:00.000Z'
  },
  {
    id: 'e-blood',
    kind: 'world',
    name: 'Blood magic',
    template: 'structured',
    fields: { category: 'Magic system', rules: 'Every spell costs the caster a memory.' },
    body: null,
    image: null,
    tagId: null,
    aliases: [],
    origin: 'author',
    status: 'canon',
    extraFields: [],
    sync: NO_SHEET_SYNC,
    created: '2026-09-04T10:00:00.000Z',
    modified: '2026-09-04T10:00:00.000Z'
  },
  {
    id: 'e-guild',
    kind: 'world',
    name: 'The Guild',
    template: 'structured',
    fields: { category: 'Culture' },
    body: null,
    image: null,
    tagId: null,
    aliases: [],
    origin: 'author',
    status: 'canon',
    extraFields: [],
    sync: NO_SHEET_SYNC,
    created: '2026-09-05T10:00:00.000Z',
    modified: '2026-09-05T10:00:00.000Z'
  }
]
