import type { Channel } from '@shared/ipc/contract'

/**
 * What each IPC channel does to a project, for the read-only state after the trial
 * (AI-BILLING-SPEC M1, `AppAccessService`). A `Record` over every channel, so a new channel does
 * not compile until someone decides which it is.
 *
 * - `write` changes what the author wrote: the manuscript, notes, sheets, tags, drafts,
 *   snapshots, imports. Refused after the trial without the license.
 * - `ai` runs a model. It passes this gate and is refused by the AI request path instead, so the
 *   answer arrives as the usual AI failure (`TRIAL_ENDED`) rather than an IPC error.
 * - `read` is everything else: reading, searching, export, backup (and restore), the account and
 *   the purchase, app-wide settings, and the project's view preferences (layout, session, focus,
 *   editor and AI settings, goals, backgrounds), which keep the read-only app usable and change
 *   nothing the author wrote (decided by Claude, unconfirmed; `QUESTIONS.md`).
 */
export type ChannelAccess = 'read' | 'write' | 'ai'

export const CHANNEL_ACCESS: Record<Channel, ChannelAccess> = {
  'app:info': 'read',
  'app:getAccess': 'read',
  'project:create': 'write',
  'project:open': 'read',
  'project:close': 'read',
  'project:current': 'read',
  'recents:list': 'read',
  'recents:remove': 'read',
  'tree:list': 'read',
  'tree:create': 'write',
  'tree:rename': 'write',
  'tree:duplicate': 'write',
  'tree:delete': 'write',
  'tree:move': 'write',
  'document:get': 'read',
  'document:save': 'write',
  'notes:get': 'read',
  'notes:save': 'write',
  'recovery:stash': 'write',
  'recovery:clear': 'read',
  'recovery:list': 'read',
  'recovery:restore': 'write',
  // Kept until the author can restore it: discarding unsaved text is not read-only.
  'recovery:discard': 'write',
  'sceneMeta:get': 'read',
  'sceneMeta:set': 'write',
  'editorSettings:get': 'read',
  'editorSettings:set': 'read',
  'aiSettings:get': 'read',
  'aiSettings:set': 'read',
  'presets:get': 'read',
  'presets:set': 'read',
  'structure:get': 'read',
  'structure:set': 'write',
  'timeline:get': 'read',
  'timeline:set': 'write',
  'focusSettings:get': 'read',
  'focusSettings:set': 'read',
  'session:get': 'read',
  'session:set': 'read',
  'authorRules:get': 'read',
  'authorRules:set': 'write',
  'background:list': 'read',
  'background:add': 'read',
  'background:remove': 'read',
  'reference:get': 'read',
  'reference:set': 'read',
  'reference:addImages': 'write',
  'goals:get': 'read',
  'goals:set': 'read',
  'stats:wordCount': 'read',
  'stats:dashboard': 'read',
  'manuscript:compile': 'read',
  'export:run': 'read',
  'compile:source': 'read',
  // Compiling writes a file outside the project, like export: read.
  'compile:run': 'read',
  // Compile preferences (format, output, scope, include ticks) are like export: read.
  'compileState:get': 'read',
  'compileState:set': 'read',
  'bookDetails:get': 'read',
  // Book details hold the author's own text (dedication, about the author): write.
  'bookDetails:set': 'write',
  'bookDetails:setCover': 'write',
  'bookDetails:removeCover': 'write',
  // App-wide settings, like the tag templates.
  'compileFormat:list': 'read',
  'compileFormat:create': 'read',
  'compileFormat:save': 'read',
  'compileFormat:delete': 'read',
  'tag:list': 'read',
  'tag:create': 'write',
  'tag:update': 'write',
  'tag:delete': 'write',
  'tag:loadTemplate': 'write',
  'tag:loadCustomTemplate': 'write',
  'tagTemplate:list': 'read',
  'tagTemplate:save': 'read',
  'tagTemplate:update': 'read',
  'tagTemplate:delete': 'read',
  'tag:recolor': 'write',
  'tag:deleteMany': 'write',
  'tag:merge': 'write',
  'tag:aliases': 'read',
  'tag:export': 'read',
  'tag:import': 'write',
  'documentTag:list': 'read',
  'documentTag:add': 'write',
  'documentTag:remove': 'write',
  'documentTag:listAll': 'read',
  'mention:listForTag': 'read',
  'mention:listForNode': 'read',
  'tag:proposed': 'read',
  'tag:dismissProposed': 'write',
  'tag:dismissedNames': 'read',
  'search:query': 'read',
  'replace:preview': 'read',
  'replace:commit': 'write',
  'replace:undo': 'write',
  'entity:list': 'read',
  'entity:get': 'read',
  'entity:create': 'write',
  'entity:update': 'write',
  'entity:setImage': 'write',
  'entity:removeImage': 'write',
  'entity:linkTag': 'write',
  'entity:delete': 'write',
  'entity:export': 'read',
  'entity:importOpen': 'read',
  'entity:importCommit': 'write',
  'library:list': 'read',
  'library:choose': 'read',
  'library:add': 'write',
  'library:addData': 'write',
  'library:open': 'read',
  'library:estimate': 'read',
  'library:process': 'ai',
  'library:apply': 'write',
  'observedFact:listForEntity': 'read',
  'observedFact:setHidden': 'write',
  'layout:get': 'read',
  'layout:set': 'read',
  'account:getStatus': 'read',
  'account:requestLink': 'read',
  'account:cancelLink': 'read',
  'account:signOut': 'read',
  'account:refresh': 'read',
  'account:getCredits': 'read',
  'account:buyCredits': 'read',
  'account:getUsage': 'read',
  'account:getPricing': 'read',
  'account:getSupporter': 'read',
  'account:refreshSupporter': 'read',
  'account:buySupporter': 'read',
  'account:setAccent': 'read',
  'updates:getState': 'read',
  'updates:check': 'read',
  'updates:setChannel': 'read',
  'updates:setAutoCheck': 'read',
  'updates:markSeen': 'read',
  'updates:install': 'read',
  'backups:get': 'read',
  'backups:setSettings': 'read',
  'backups:chooseFolder': 'read',
  'backups:now': 'read',
  'backups:reveal': 'read',
  'backups:restore': 'read',
  'drafts:list': 'read',
  'drafts:switch': 'write',
  'drafts:duplicate': 'write',
  'drafts:rename': 'write',
  'drafts:delete': 'write',
  'drafts:compare': 'read',
  'drafts:revert': 'write',
  'snapshots:list': 'read',
  'snapshots:take': 'write',
  'snapshots:update': 'write',
  'snapshots:delete': 'write',
  'snapshots:compare': 'read',
  'snapshots:restore': 'write',
  'diagnostics:getState': 'read',
  'diagnostics:setEnabled': 'read',
  'diagnostics:reportRendererError': 'read',
  'devtools:getState': 'read',
  'devtools:setEnabled': 'read',
  'devtools:snapshot': 'read',
  'devtools:requestText': 'read',
  'devtools:log': 'read',
  'devtools:ghostSkip': 'read',
  'devtools:clear': 'read',
  'devtools:openChromium': 'read',
  'devtools:report': 'read',
  'ai:getStatus': 'read',
  'ai:setKey': 'read',
  'ai:clearKey': 'read',
  'ai:setOwnKeyProvider': 'read',
  'ai:getModelChoice': 'read',
  'ai:setRouting': 'read',
  'ai:usageHistory': 'read',
  'ai:testConnection': 'read',
  'ai:setModels': 'read',
  'ai:setLocalEndpoint': 'read',
  'ai:usageSummary': 'read',
  'ai:setDailyCap': 'read',
  'ai:recommendTags': 'ai',
  'ai:cancel': 'read',
  'ai:ghostText': 'ai',
  'ai:chat': 'ai',
  'ai:agent': 'ai',
  'ai:query': 'ai',
  'ai:rewrite': 'ai',
  'ai:critique': 'ai',
  'ai:continuity': 'ai',
  'ai:proofread': 'ai',
  'editPass:start': 'ai',
  'editPass:resume': 'ai',
  'editPass:cancel': 'read',
  'editPass:list': 'read',
  'editPass:get': 'read',
  'editPass:delete': 'write',
  'editPass:changes': 'read',
  'editPass:settle': 'write',
  'editPass:presets': 'read',
  'editPass:setPresets': 'read',
  'ai:whatNext': 'ai',
  'ai:route': 'ai',
  'ai:suggestSynopsis': 'ai',
  'ai:suggestNotes': 'ai',
  'continuity:list': 'read',
  'continuity:settle': 'write',
  'ai:betaReader': 'ai',
  'ai:draftBrief': 'ai',
  'summary:get': 'read',
  'ai:summarize': 'ai',
  'jobs:status': 'read',
  'jobs:cancel': 'read',
  'jobs:resume': 'ai',
  'jobs:indexAll': 'ai',
  'conversations:get': 'read',
  'conversations:set': 'read',
  'proposal:settle': 'write',
  'proposal:pendingTags': 'read',
  'voice:listExemplars': 'read',
  'voice:addExemplar': 'write',
  'voice:removeExemplar': 'write',
  'voice:notes': 'read',
  'voice:clearNotes': 'write',
  'voice:profile': 'read',
  'voice:consistencyReport': 'read',
  'provenance:report': 'read',
  'provenance:export': 'read',
  'import:open': 'read',
  'import:commit': 'write',
  'import:createProject': 'write',
  'import:detectStructure': 'ai',
  'window:close': 'read',
  'window:close-cancelled': 'read',
  'window:setFullScreen': 'read',
  'view:get': 'read',
  'view:zoomDocument': 'read',
  'view:setUiScale': 'read',
  'view:setPageEdges': 'read',
  'view:setTheme': 'read',
  'view:saveCustomTheme': 'read',
  'view:deleteCustomTheme': 'read',
  'startup:get': 'read',
  'startup:setReopenLastProject': 'read',
  'menu:edit': 'read',
  'dictionary:get': 'read',
  'dictionary:add': 'write',
  'dictionary:remove': 'write',
  'dictionary:notName': 'write',
  'spellcheck:replace': 'write',
  'menu:openExternal': 'read'
}

/** Whether a channel is refused while the app is read-only. */
export function isWriteChannel(channel: Channel): boolean {
  return CHANNEL_ACCESS[channel] === 'write'
}
